version: "3.9"
services:
    website:
        image: dualvs/fnfcentral:local
        depends_on:
            - website-migrate
            - sqldb
            - questdb
        environment:
            DATABASE_URL: postgresql://postgres:password@sqldb:5432/postgres?sslmode=allow&schema=api
            KRATOS_URL: kratos:4433
            LDAP_URL: ldap://ldap:389
            LDAP_BIND_DN: cn=admin,dc=fnfcentral,dc=com
            LDAP_BIND_PASS: admin_pass
            LDAP_SEARCH_BASE: dc=fnfcentral,dc=com
            LDAP_SEARCH_FILTER: (cn={{username}})
            JWT_SECRET: superSecret

    website-migrate:
        image: dualvs/fnfcentral:local
        command: npx prisma migrate deploy
        depends_on:
            - sqldb
        environment:
            DATABASE_URL: postgresql://postgres:password@sqldb:5432/postgres?sslmode=allow&schema=api

    nginx:
        build: ./testing_nginx
        depends_on:
            - frontend
            - website
            - kratos
            - byebyemail
            - ipfs0
        ports:
            - 80:80
            - 443:443

    nginx-exporter:
        image: nginx/nginx-prometheus-exporter
        depends_on:
            - nginx
        command: -nginx.scrape-uri=http://nginx:8080/status

    ldap:
        image: dualvs/fnfcentral-testing_ldap:local
        environment:
            LDAP_ADMIN_PASSWORD: admin_pass
            LDAP_BASE_DN: dc=fnfcentral,dc=com
        ports:
            - 389:389
        volumes:
            - ldap_data:/var/lib/ldap
            - ldap_config:/etc/ldap/slapd.d

    ldap_admin:
        image: osixia/phpldapadmin:0.7.2
        ports:
            - 8090:80
        environment:
            PHPLDAPADMIN_LDAP_HOSTS: ldap
            PHPLDAPADMIN_HTTPS: "false"

    kratos-migrate:
        image: dualvs/fnfcentral-kratos:local
        depends_on:
            - sqldb
        command: migrate --config /home/ory/kratos.yml sql -e --yes
        environment:
            DSN: "postgres://postgres:password@sqldb:5432/postgres?sslmode=allow"
            SELFSERVICE_DEFAULT_BROWSER_RETURN_URL: "https://local.fnfcentral.com/dashboard"
            SELFSERVICE_WHITELISTED_RETURN_URLS: "https://local.fnfcentral.com"
            SERVE_PUBLIC_BASE_URL: "https://user.local.fnfcentral.com"
            COURIER_SMTP_CONNECTION_URI: "smtps://test:test@byebyemail:1025/?skip_ssl_verify=true&legacy_ssl=true"
            COURIER_SMTP_FROM_ADDRESS: "no-reply@local.fnfcentral.com"
            SESSION_COOKIE_DOMAIN: "local.fnfcentral.com"
        restart: on-failure

    kratos:
        image: dualvs/fnfcentral-kratos:local
        depends_on:
            - kratos-migrate
            - sqldb
        command: serve --watch-courier --config /home/ory/kratos.yml
        environment:
            DSN: "postgres://postgres:password@sqldb:5432/postgres?sslmode=allow"
            SELFSERVICE_DEFAULT_BROWSER_RETURN_URL: "https://local.fnfcentral.com/dashboard"
            SELFSERVICE_WHITELISTED_RETURN_URLS: "https://local.fnfcentral.com"
            SERVE_PUBLIC_BASE_URL: "https://user.local.fnfcentral.com"
            COURIER_SMTP_CONNECTION_URI: "smtps://test:test@byebyemail:1025/?skip_ssl_verify=true&legacy_ssl=true"
            COURIER_SMTP_FROM_ADDRESS: "no-reply@local.fnfcentral.com"
            SESSION_COOKIE_DOMAIN: "local.fnfcentral.com"
            LOG_LEAK_SENSITIVE_VALUES: "true"
        ports:
            - 4434:4434

    byebyemail:
        image: oryd/mailslurper:latest-smtps
        ports:
            - 4436:4436
            - 4437:4437

    sqldb:
        image: postgres:14-alpine
        ports:
            - 5555:5432
        environment:
            POSTGRES_PASSWORD: password
        volumes:
            - sqldb_data:/var/lib/postgresql/data

    questdb:
        image: questdb/questdb
        ports:
            - 9000:9000
            - 9009:9009
            - 8812:8812
            - 9003:9003
        volumes:
            - questdb_data:/root/.questdb/

    postgres-exporter:
        image: quay.io/prometheuscommunity/postgres-exporter
        depends_on:
            - sqldb
        environment:
            DATA_SOURCE_NAME: postgresql://postgres:password@sqldb:5432/postgres?sslmode=allow
            PG_EXPORTER_AUTO_DISCOVER_DATABASES: "true"

    prometheus:
        image: dualvs/fnfcentral-testing_metrics:local
        depends_on:
            - nginx-exporter
            - kratos
            - postgres-exporter

    grafana:
        image: grafana/grafana
        depends_on:
            - prometheus
        volumes:
            - grafana_data:/var/lib/grafana

    # File Servers
    builds:
        image: nginx
        volumes:
            - ./files/builds:/usr/share/nginx/html
    
    files:
        image: nginx
        volumes:
            - ./files/files:/usr/share/nginx/html

    games:
        image: nginx
        volumes:
            - ./files/games:/usr/share/nginx/html

volumes:
    sqldb_data:

    questdb_data:

    grafana_data:

    ldap_data:

    ldap_config:
