version: "3.9"
services:
    frontend:
        build: ./frontend

    api:
        build: ./api
        depends_on:
            - api-migrate
            - sqldb
        environment:
            DATABASE_URL: postgresql://postgres:password@sqldb:5432/postgres?sslmode=allow&schema=api
            LDAP_URL: ldap://ldap:389
            LDAP_BIND_DN: cn=admin,dc=fnfcentral,dc=com
            LDAP_BIND_PASS: admin_pass
            LDAP_SEARCH_BASE: dc=fnfcentral,dc=com
            LDAP_SEARCH_FILTER: (cn={{username}})
            JWT_SECRET: superSecret

    api-migrate:
        build: ./api
        command: npx prisma migrate deploy
        depends_on:
            - sqldb
        environment:
            DATABASE_URL: postgresql://postgres:password@sqldb:5432/postgres?sslmode=allow&schema=api

    nginx:
        build: ./testing_nginx
        depends_on:
            - frontend
            - api
            - raw
            - kratos
            - byebyemail
        ports:
            - 80:80
            - 443:443

    nginx-exporter:
        image: nginx/nginx-prometheus-exporter
        depends_on:
            - nginx
        command: -nginx.scrape-uri=http://nginx:8080/status

    raw:
        build: ./testing_raw

    ldap:
        build: ./testing_ldap
        environment:
            LDAP_ADMIN_PASSWORD: admin_pass
            LDAP_BASE_DN: dc=fnfcentral,dc=com
        ports:
            - 389:389
        volumes:
            - ldap_data:/var/lib/ldap
            - ldap_config:/etc/ldap/slapd.d

    ldap_admin:
        image: osixia/phpldapadmin:0.7.2
        ports:
            - 8090:80
        environment:
            PHPLDAPADMIN_LDAP_HOSTS: ldap
            PHPLDAPADMIN_HTTPS: "false"

    minio:
        image: quay.io/minio/minio
        command: server /data --console-address ":9001"
        environment:
            MINIO_ROOT_USER: minio
            MINIO_ROOT_PASSWORD: minio123
        volumes:
            - raw_data:/data
        ports:
            - 9000:9000
            - 9001:9001

    kratos-migrate:
        build: ./kratos
        depends_on:
            - sqldb
        command: migrate --config /home/ory/kratos.yml sql -e --yes
        restart: on-failure

    kratos:
        build: ./kratos
        depends_on:
            - kratos-migrate
            - sqldb
        command: serve --watch-courier --config /home/ory/kratos.yml
        environment:
            LOG_LEAK_SENSITIVE_VALUES: "true"
        ports:
            - 4434:4434

    byebyemail:
        image: oryd/mailslurper:latest-smtps
        ports:
            - 4436:4436
            - 4437:4437

    sqldb:
        image: timescale/timescaledb:latest-pg12
        ports:
            - 5555:5432
        environment:
            POSTGRES_PASSWORD: password
        volumes:
            - sqldb_data:/var/lib/postgresql/data

    postgres-exporter:
        image: quay.io/prometheuscommunity/postgres-exporter
        depends_on:
            - sqldb
        environment:
            DATA_SOURCE_NAME: postgresql://postgres:password@sqldb:5432/postgres?sslmode=allow
            PG_EXPORTER_AUTO_DISCOVER_DATABASES: "true"

    prometheus:
        build: ./metrics
        depends_on:
            - nginx-exporter
            - kratos
            - postgres-exporter
            - promscale

    promscale:
        image: timescale/promscale
        depends_on:
            - sqldb
        environment:
            PROMSCALE_DB_CONNECT_RETRIES: 10
            PROMSCALE_DB_URI: postgres://postgres:password@sqldb:5432/postgres?sslmode=allow

    grafana:
        image: grafana/grafana
        depends_on:
            - prometheus
        volumes:
            - grafana_data:/var/lib/grafana

volumes:
    raw_data:

    sqldb_data:

    grafana_data:

    ldap_data:

    ldap_config:
