version: "3.9"
services:
    frontend:
        build: ./frontend

    website:
        build: ./website
        environment:
            DATABASE_URL: postgresql://postgres:password@sqldb:5432/postgres?sslmode=allow&schema=api
            LDAP_URL: ldap://ldap:389
            LDAP_BIND_DN: cn=admin,dc=fnfcentral,dc=com
            LDAP_BIND_PASS: admin_pass
            LDAP_SEARCH_BASE: dc=fnfcentral,dc=com
            LDAP_SEARCH_FILTER: (cn={{username}})
            JWT_SECRET: superSecret
            IPFS_CLIENT_API: ipfs0:5001
            IPFS_CLUSTER_API: cluster0:9094

    api:
        build: ./api
        depends_on:
            - api-migrate
            - sqldb
        environment:
            DATABASE_URL: postgresql://postgres:password@sqldb:5432/postgres?sslmode=allow&schema=api
            LDAP_URL: ldap://ldap:389
            LDAP_BIND_DN: cn=admin,dc=fnfcentral,dc=com
            LDAP_BIND_PASS: admin_pass
            LDAP_SEARCH_BASE: dc=fnfcentral,dc=com
            LDAP_SEARCH_FILTER: (cn={{username}})
            JWT_SECRET: superSecret
            IPFS_CLIENT_API: ipfs0:5001
            IPFS_CLUSTER_API: cluster0:9094

    api-migrate:
        build: ./api
        command: npx prisma migrate deploy
        depends_on:
            - sqldb
        environment:
            DATABASE_URL: postgresql://postgres:password@sqldb:5432/postgres?sslmode=allow&schema=api

    nginx:
        build: ./testing_nginx
        depends_on:
            - frontend
            - api
            - kratos
            - byebyemail
            - ipfs0
        ports:
            - 80:80
            - 443:443

    nginx-exporter:
        image: nginx/nginx-prometheus-exporter
        depends_on:
            - nginx
        command: -nginx.scrape-uri=http://nginx:8080/status

    ldap:
        build: ./testing_ldap
        environment:
            LDAP_ADMIN_PASSWORD: admin_pass
            LDAP_BASE_DN: dc=fnfcentral,dc=com
        ports:
            - 389:389
        volumes:
            - ldap_data:/var/lib/ldap
            - ldap_config:/etc/ldap/slapd.d

    ldap_admin:
        image: osixia/phpldapadmin:0.7.2
        ports:
            - 8090:80
        environment:
            PHPLDAPADMIN_LDAP_HOSTS: ldap
            PHPLDAPADMIN_HTTPS: "false"

    kratos-migrate:
        build: ./kratos
        depends_on:
            - sqldb
        command: migrate --config /home/ory/kratos.yml sql -e --yes
        restart: on-failure

    kratos:
        build: ./kratos
        depends_on:
            - kratos-migrate
            - sqldb
        command: serve --watch-courier --config /home/ory/kratos.yml
        environment:
            LOG_LEAK_SENSITIVE_VALUES: "true"
        ports:
            - 4434:4434

    byebyemail:
        image: oryd/mailslurper:latest-smtps
        ports:
            - 4436:4436
            - 4437:4437

    sqldb:
        image: timescale/timescaledb:latest-pg12
        ports:
            - 5555:5432
        environment:
            POSTGRES_PASSWORD: password
        volumes:
            - sqldb_data:/var/lib/postgresql/data

    postgres-exporter:
        image: quay.io/prometheuscommunity/postgres-exporter
        depends_on:
            - sqldb
        environment:
            DATA_SOURCE_NAME: postgresql://postgres:password@sqldb:5432/postgres?sslmode=allow
            PG_EXPORTER_AUTO_DISCOVER_DATABASES: "true"

    prometheus:
        build: ./metrics
        depends_on:
            - nginx-exporter
            - kratos
            - postgres-exporter
            - promscale

    promscale:
        image: timescale/promscale
        depends_on:
            - sqldb
        environment:
            PROMSCALE_DB_CONNECT_RETRIES: 10
            PROMSCALE_DB_URI: postgres://postgres:password@sqldb:5432/postgres?sslmode=allow

    grafana:
        image: grafana/grafana
        depends_on:
            - prometheus
        volumes:
            - grafana_data:/var/lib/grafana

    # Testing IPFS Cluster
    ipfs0:
        container_name: ipfs0
        image: ipfs/go-ipfs:latest
        ports:
            - 4001:4001
            - 5001:5001
            - 8080:8080
        volumes:
            - data_ipfs0:/data/ipfs
    cluster0:
        container_name: cluster0
        image: ipfs/ipfs-cluster:latest
        depends_on:
            - ipfs0
        environment:
            CLUSTER_PEERNAME: cluster0
            CLUSTER_SECRET: 9094d40ace6208bc2d5b98b10044e5d5a80c30f7c7c51abdde49936af8e5e977
            CLUSTER_IPFSHTTP_NODEMULTIADDRESS: /dns4/ipfs0/tcp/5001
            CLUSTER_CRDT_TRUSTEDPEERS: "*"
            CLUSTER_RESTAPI_HTTPLISTENMULTIADDRESS: /ip4/0.0.0.0/tcp/9094
            CLUSTER_MONITORPINGINTERVAL: 2s
        ports:
            - "127.0.0.1:9094:9094"
        volumes:
            - data_cluster0:/data/ipfs-cluster

    ipfs1:
        container_name: ipfs1
        image: ipfs/go-ipfs:latest
        volumes:
            - data_ipfs1:/data/ipfs
    cluster1:
        container_name: cluster1
        image: ipfs/ipfs-cluster:latest
        depends_on:
            - ipfs1
        environment:
            CLUSTER_PEERNAME: cluster1
            CLUSTER_SECRET: 9094d40ace6208bc2d5b98b10044e5d5a80c30f7c7c51abdde49936af8e5e977
            CLUSTER_IPFSHTTP_NODEMULTIADDRESS: /dns4/ipfs1/tcp/5001
            CLUSTER_CRDT_TRUSTEDPEERS: "*"
            CLUSTER_MONITORPINGINTERVAL: 2s
        volumes:
            - data_cluster1:/data/ipfs-cluster

volumes:
    sqldb_data:

    grafana_data:

    ldap_data:

    ldap_config:

    # IPFS Test Cluster
    data_ipfs0:
    data_cluster0:
    data_ipfs1:
    data_cluster1:
