version: "3.9"
services:
    frontend:
        build: ./frontend

    nginx:
        build: ./testing_nginx
        ports:
            - 80:80
            - 443:443

    nginx-exporter:
        image: nginx/nginx-prometheus-exporter
        command: -nginx.scrape-uri=http://nginx:8080/status

    raw:
        build: ./testing_raw

    kratos-migrate:
        build: ./kratos
        command: migrate --config /home/ory/kratos.yml sql -e --yes
        restart: on-failure

    kratos:
        build: ./kratos
        command: serve --watch-courier --config /home/ory/kratos.yml
        environment:
            LOG_LEAK_SENSITIVE_VALUES: "true"
        ports:
            - 4434:4434

    byebyemail:
        image: oryd/mailslurper:latest-smtps
        ports:
            - 4436:4436
            - 4437:4437

    sqldb:
        image: timescale/timescaledb:latest-pg12
        ports:
            - 5555:5432
        environment:
            POSTGRES_PASSWORD: password
        volumes:
            - sqldb-data:/var/lib/postgresql/data

    postgres-exporter:
        image: quay.io/prometheuscommunity/postgres-exporter
        environment:
            DATA_SOURCE_NAME: postgresql://postgres:password@sqldb:5432/postgres?sslmode=allow
            PG_EXPORTER_AUTO_DISCOVER_DATABASES: "true"

    prometheus:
        build: ./metrics

    promscale:
        image: timescale/promscale
        environment:
            PROMSCALE_DB_CONNECT_RETRIES: 10
            PROMSCALE_DB_URI: postgres://postgres:password@sqldb:5432/postgres?sslmode=allow

    grafana:
        image: grafana/grafana
        volumes:
            - grafana-data:/var/lib/grafana

volumes:
    raw-games:

    sqldb-data:

    grafana-data:
