scrape_configs:
    - job_name: NGINX
      scrape_interval: 15s
      static_configs:
          - targets: ["nginx-exporter:9113"]
    - job_name: prometheus
      static_configs:
          - targets: ["localhost:9090"]
    - job_name: postgres
      static_configs:
          - targets: ["postgres-exporter:9187"]
    - job_name: kratos
      metrics_path: /metrics/prometheus
      static_configs:
          - targets: ["kratos:4434"]
    - job_name: fnfcentral
      static_configs:
          - targets: ["website:3000"]
