FROM osixia/openldap

local:
    ENV LDAP_ORGANISATION="FNF Central"
    ENV LDAP_DOMAIN="fnfcentral.com"

    COPY bootstrap.ldif /container/service/slapd/assets/config/bootstrap/ldif/50-bootstrap.ldif

    SAVE IMAGE dualvs/fnfcentral-testing_ldap:local