scrape_configs:
    - job_name: NGINX
      scrape_interval: 15s
      static_configs:
          - targets: ["nginx-exporter:9113"]
    - job_name: prometheus
      static_configs:
          - targets: ["localhost:9090"]
    - job_name: postgres
      static_configs:
          - targets: ["postgres-exporter:9187"]

remote_write:
    - url: http://promscale:9201/write
remote_read:
    - url: http://promscale:9201/read
      read_recent: true
